version: '3.8'
services:
  apache:
    build: 
      dockerfile: Dockerfile
    environment:
      - MYSQL_DATABASE=pr1
      - MYSQL_USER=theFirstUser
      - MYSQL_PASSWORD=theFirstUser1234
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./app
        target: /var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql
    ports:
      - 3307:3306
    volumes:
      - type: volume
        source: projet1
        target: /var/lib/mysql
      - type: bind
        source: ./mysql-init/
        target: /docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=135792468
      - MYSQL_DATABASE=pr1
      - MYSQL_USER=theFirstUser
      - MYSQL_PASSWORD=theFirstUser1234
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
volumes:
  projet1: 